/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as SampleThreeRouteImport } from './routes/sample-three'
import { Route as SampleTwoRouteImport } from './routes/sample-two'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleThreeRoute = SampleThreeRouteImport.update({
  id: '/sample-three',
  path: '/sample-three',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleTwoRoute = SampleTwoRouteImport.update({
  id: '/sample-two',
  path: '/sample-two',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sample': typeof SampleRoute
  '/sample-three': typeof SampleThreeRoute
  '/sample-two': typeof SampleTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sample': typeof SampleRoute
  '/sample-three': typeof SampleThreeRoute
  '/sample-two': typeof SampleTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sample': typeof SampleRoute
  '/sample-three': typeof SampleThreeRoute
  '/sample-two': typeof SampleTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/sample' | '/sample-three' | '/sample-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sample' | '/sample-three' | '/sample-two'
  id: '__root__' | '/' | '/login' | '/sample' | '/sample-three' | '/sample-two'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SampleRoute: typeof SampleRoute
  SampleThreeRoute: typeof SampleThreeRoute
  SampleTwoRoute: typeof SampleTwoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-three': {
      id: '/sample-three'
      path: '/sample-three'
      fullPath: '/sample-three'
      preLoaderRoute: typeof SampleThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-two': {
      id: '/sample-two'
      path: '/sample-two'
      fullPath: '/sample-two'
      preLoaderRoute: typeof SampleTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SampleRoute: SampleRoute,
  SampleThreeRoute: SampleThreeRoute,
  SampleTwoRoute: SampleTwoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
